services:
  - type: web
    name: aggrsite
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: AUTH_TOKEN
        sync: false
      - key: TZ
        value: Asia/Shanghai
      - key: PORT
        value: "4000"
      - key: DB_TYPE
        value: sqlite
      - key: DB_URL
        sync: false
      - key: CHECKIN_CRON
        value: "0 8 * * *"
      - key: BALANCE_REFRESH_CRON
        value: "0 * * * *"
      - key: DATA_DIR
        value: "/app/data"
